### PR TITLE
Add lifecycle order table for quicker scanability of capabilities

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
I find this layout of data easier to read. :man_shrugging: maybe other people do to?

### CODE REVIEW

**Comment by chancancode** [comment]
@NullVoxPopuli seems good to me! Can you file it against https://github.com/sukima/ember-class-based-modifier? Sorry about that!

**Comment by chancancode** [comment]
@NullVoxPopuli Also, How about we flip the table around to something like this:

```
                      | Install | Update | Remove | this.element |   this.args   | 
----------------------+---------+--------+--------+--------------+---------------+-----
constructor()         |   (1)   |    x   |   x    |       x      | after super() | 
didUpdateArguments()  |    x    |   (1)  |   x    |       v      |       v       | ...
didReceiveArguments() |   (2)   |   (2)  |   x    |       v      |       v       | ...
didInstall()          |   (3)   |    x   |   x    |       v      |       v       |
willRemove()          |    x    |    x   |  (1)   |       v      |       v       |
willDestroy()         |    x    |    x   |  (2)   |       x      |       v       |
```

(The emojis are HTML formatting are good, I'm just too lazy to replicate it in the comment)

**Comment by NullVoxPopuli** [comment]
ooo, I like that

**Comment by NullVoxPopuli** [comment]
Cleaning up my list of PRs (list at: https://github.com/pulls). If any of this work is still useful, feel free to cherry-pick.

**Pull request closed without merging**
